<?xml version="1.0"?>

<robot name="sensor" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="box_height" value="0.2" />
  <xacro:property name="box_width" value="0.2" />
	<!--
 	<link name="world"/>
  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>
  -->
  <link name="base_link">
    
    <collision>
      <origin xyz="0 0 ${box_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${box_width} ${box_width} ${box_height}"/>
      </geometry>
    </collision>
    <!--
    <visual>
      <origin xyz="0 0 ${box_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${box_width} ${box_width} ${box_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    -->
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
    
  </link>
  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>
 <gazebo reference="sensor">
    <material>Gazebo/Blue</material>
  </gazebo>
</robot>
